### ISSUE TITLE
Clearance...

### ISSUE THREAD

**Issue by Durahl** [gneu42/Triple-Decky#4]
With one of the ECAS04 Fittings having come loose on my Stock ERCF I decided to give the whole thing an overhaul including the SturdyBunny, Springy, and... well... TrippleDecky 😑

While the first two worked without issues I cannot say the same for the TrippleDecky which I mostly attribute to the use of _terrible_ if at all use of clearances and lack of documentation of how the system should behave _in operation_ ( like a Video showcasing if parts should fit loose or in tension together?! ).

**First, the _very_ Obvious:**
![IMG](https://i.imgur.com/KmtZ6oT.png)
Both the stationary `Base` as well as the `Filament Path` have the same height on the Build Plate thus resulting in the same width on the Extrusion.

Everyone _packing_ the `Bases` together as tight as possible to honor the concept of a **Sturdy**Bunny will essentially _also_ pack the `Filament Paths` together resulting in them binding against each other.
Everyone leaving a gap between the Bases via the use of like a paper shim during assembly will defeat the concept of a SturdyBunny.

The _obvious_ choice is to increase the Z-Height of the `Base` on the Build Plate by at least 1 if not 2 Layers.

**Next, the Questionable:**
![IMG](https://i.imgur.com/iWCo5vA.png)
Even with the above-mentioned Hack I couldn't get the `Filament Path` parts to move _reliably_ free despite the use of 4 Magnets like how it is happening with regular `Blocks` and the `Top Hats` on the Stock / SturdyBunny Variants. And the parts print to spec because the `MR85ZZ Bearings` do fit nicely!

This I attribute in parts to how the `Trap` is getting caught in the square hole of the `Filament Path` it is supposed to reside in but also how there's essentially NO clearance whatsoever between the Hinge Areas of the `Base` and `Filament Path` as can be seen above.

**Finally, the Unknown:**
Is the `Integrated Top Hat` supposed to be floppy like on a Stock / SturdyBunny or is it supposed to be press fit tight with the `Filament Path`? Who knows... Mine wouldn't move on their own once attached to the Filament Paths and while them not moving freely wouldn't make much of a difference in the grand scheme of things it then kinda begs the question why they're a separate part from the `Filament Path` to begin with?

**Verdict:**
Didn't work out for me... At the end of the day the amount of pressure required to overcome the tension in the System for the Filament to even just remotely reliably getting fed through the Tube would have exceeded the strength of a SAVOX SH-0254 getting past the Springys spring tension.

So SturdyBunny / Springy which is working like a charm ( after splicing my own _working_ `Integrated Top Hat` together ) it is for me.

**Comment by gneu42** [comment]
I'm sorry that TD did not work for you.

Triple Decky was designed to solve only 1 problem. That is the filament going out of the block either forward or backward when loading/unloading other tools. If you do not have that problem, then you don't need it. You can go with the original design from Sturdy Bunny, and keep the magnetic gates. 

The very obvious : looking at your pictures, you are not printing it the way you should. If you print all the parts separately, and if YOUR PRINTER IS WELL TUNED, and you use the correct profile (e.g. from Andrew Ellis like it is mentioned in the readme file). The hinged parts should go together without any force nor clean up, beside  very little cleaning where the support was located and what is described in the cleaning tips on the readme file. Lots of people have print TD without issues. 
Also, 3D printers are not precisions machines like a mill or a lath. It is impossible to make STL for each printers. A lots of variables can affect the way parts fit together, filament type/brand, temperature... If with your set up, you can't get them to fit nicely, then you can always file / sand the area that are causing problems. With all the feedback I get, it seems that it works very well for lots of people.

Bunny is sturdy because of the 2020 extrusion, not with packing the gates together as hard as possible. It is not necessary to pack all the block together like on V1. Just put all the blocks next to each other and all will be fine. However I agree that both parts have the same width, and I'm looking to make a small change in that respect. Unfortunately, I can't do it right now. I not at home at the moment, and can't test.

Concerning clearance, I will not change anything because it works just fine the way it is for the vast majority of people who have printed them.
However, if you wait for the V2 public release, you will have access to the CAD file and then you can modify whatever you like.

The top hat should be freely moving on its hinge and not floppy like on V1.

I will also try to make a small video showing how parts are fitting together. This might take some time because I may not have everything handy where I am right now.

I will make a small modification just for you to try concerning the width of the filament path (it will be reduced by 1 layer) and send it to you via discord DM.

**Comment by Durahl** [comment]
I think it goes without saying that I did _NOT_ print the `Base` and `Filament Path` in a print in place assembled state.
Them being pictured like that in the Slicer was to show the lack of clearance between the two parts from even just a Slicer PoV.

My Printer is tuned well enough hence my comment about the MR85ZZ Bearings fitting nicely in their Bearing Pockets.
If they were loose or hard to press in, they'd be an indicator of something being off but that is not the case.

3D Printers not being CNC Precision Machines capable of holding 1/100th of a Millimeter Tolerances is the _very_ reason why such Projects should be designed with loser Tolerances in mind which clearly isn't the case. Just saying "It works for some" is no basis for sticking with it. Might as well close this Bug Report section altogether! Neither is telling ppl to whip out a File / Sanding Paper and go ham on the parts until they fit - Especially since for anyone with this issue it won't even be clear where the problem is.

If you're asking for such tight tolerances nearing that of a CNC then it is your job as the Author to either account for variances in Printers, Materials, and Slicers **_OR_** providing the _exact_ settings for the Machine, Slicer, and Material you can guarantee your Project will work with. Everything else is just wasting ppls Time and Materials - Especially those willing to giving it a try and contributing to making it better.

But you've made your point it is not worth further investigating the TrippleDecky since you're not even willing in making such a miniscule change like adding a mere 1-2 additional Layers to the `Base` to aid against the friction between the `Filament Path` as such I will stop providing suggestions based on my experience in making it an _universally_ reliable product for _everyone_ instead of just the lucky few that won the Machine, Slicer, and Material Lottery.
